# Generated by Django 5.2.13 on 2026-05-07 11:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_session_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("200"), max_digits=10
                    ),
                ),
                (
                    "prayer_buffer_minutes",
                    models.IntegerField(
                        default=10,
                        help_text="Legacy single buffer time after Adhan (deprecated)",
                    ),
                ),
                (
                    "fajr_iqama_delay",
                    models.IntegerField(
                        default=10,
                        help_text="Iqama delay for Fajr in minutes (e.g. 20)",
                    ),
                ),
                (
                    "dhuhr_iqama_delay",
                    models.IntegerField(
                        default=10,
                        help_text="Iqama delay for Dhuhr in minutes (e.g. 10)",
                    ),
                ),
                (
                    "asr_iqama_delay",
                    models.IntegerField(
                        default=10, help_text="Iqama delay for Asr in minutes (e.g. 15)"
                    ),
                ),
                (
                    "maghrib_iqama_delay",
                    models.IntegerField(
                        default=10,
                        help_text="Iqama delay for Maghrib in minutes (e.g. 5)",
                    ),
                ),
                (
                    "isha_iqama_delay",
                    models.IntegerField(
                        default=10,
                        help_text="Iqama delay for Isha in minutes (e.g. 10)",
                    ),
                ),
                (
                    "fajr_post_block",
                    models.IntegerField(
                        default=15,
                        help_text="Post-iqama blocking duration for Fajr in minutes",
                    ),
                ),
                (
                    "dhuhr_post_block",
                    models.IntegerField(
                        default=15,
                        help_text="Post-iqama blocking duration for Dhuhr in minutes",
                    ),
                ),
                (
                    "asr_post_block",
                    models.IntegerField(
                        default=15,
                        help_text="Post-iqama blocking duration for Asr in minutes",
                    ),
                ),
                (
                    "maghrib_post_block",
                    models.IntegerField(
                        default=15,
                        help_text="Post-iqama blocking duration for Maghrib in minutes",
                    ),
                ),
                (
                    "isha_post_block",
                    models.IntegerField(
                        default=15,
                        help_text="Post-iqama blocking duration for Isha in minutes",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.CreateModel(
            name="RecurringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (5, "Saturday"),
                            (6, "Sunday"),
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to temporarily pause this schedule",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="SessionDurationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        help_text="Duration in minutes (e.g. 30, 60)", unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["duration_minutes"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("", "Select country…"),
                            ("Egypt", "🇪🇬 Egypt"),
                            ("Germany", "🇩🇪 Germany"),
                            ("France", "🇫🇷 France"),
                            ("United Kingdom", "🇬🇧 United Kingdom"),
                            ("United States", "🇺🇸 United States"),
                            ("Canada", "🇨🇦 Canada"),
                            ("Saudi Arabia", "🇸🇦 Saudi Arabia"),
                            ("UAE", "🇦🇪 UAE"),
                            ("Kuwait", "🇰🇼 Kuwait"),
                            ("Lebanon", "🇱🇧 Lebanon"),
                            ("Jordan", "🇯🇴 Jordan"),
                            ("Iraq", "🇮🇶 Iraq"),
                            ("Japan", "🇯🇵 Japan"),
                            ("China", "🇨🇳 China"),
                            ("India", "🇮🇳 India"),
                            ("Australia", "🇦🇺 Australia"),
                        ],
                        default="Egypt",
                        max_length=100,
                    ),
                ),
                (
                    "session_duration",
                    models.IntegerField(default=60, help_text="Duration in minutes"),
                ),
                (
                    "session_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("200"), max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "prayer",
                    models.CharField(
                        choices=[
                            ("fajr", "Fajr"),
                            ("dhuhr", "Dhuhr"),
                            ("asr", "Asr"),
                            ("maghrib", "Maghrib"),
                            ("isha", "Isha"),
                        ],
                        max_length=10,
                    ),
                ),
                ("adhan_time", models.TimeField()),
                (
                    "duration",
                    models.IntegerField(
                        default=30,
                        help_text="Blocked duration in minutes for this prayer",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "adhan_time"],
                "unique_together": {("date", "prayer")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("skip", "Skip Week"),
                            ("move", "Move Session"),
                            ("add", "Add Sessions"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(
                        help_text="Start date (Monday) of the week affected"
                    ),
                ),
                (
                    "move_to_date",
                    models.DateField(
                        blank=True,
                        help_text="Target date for moving the session",
                        null=True,
                    ),
                ),
                (
                    "move_to_time",
                    models.TimeField(
                        blank=True,
                        help_text="Target time for the moved session",
                        null=True,
                    ),
                ),
                (
                    "add_count",
                    models.IntegerField(
                        default=1, help_text="Number of extra sessions to add"
                    ),
                ),
                (
                    "add_date",
                    models.DateField(
                        blank=True, help_text="Date to add extra sessions", null=True
                    ),
                ),
                (
                    "add_time",
                    models.TimeField(
                        blank=True, help_text="Time to add extra sessions", null=True
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why this exception exists",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Who created this exception",
                        max_length=100,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="scheduler.recurringschedule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schedule Exceptions",
                "ordering": ["week_start_date"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("attended", "Attended ✅"),
                            ("absent", "Absent (No-Show) ❌"),
                            ("excused", "Excused (No Pay) 💬"),
                            ("cancelled_by_teacher", "Cancelled by Tutor 🚫"),
                        ],
                        default="scheduled",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="scheduler.student",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="recurringschedule",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="scheduler.student",
            ),
        ),
    ]
