# Generated by Django 5.2.13 on 2026-05-06 22:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_session_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("200"), max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.CreateModel(
            name="SessionDurationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        help_text="Duration in minutes (e.g. 30, 60)", unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["duration_minutes"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "session_duration",
                    models.IntegerField(default=60, help_text="Duration in minutes"),
                ),
                (
                    "session_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("200"), max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "prayer",
                    models.CharField(
                        choices=[
                            ("fajr", "Fajr"),
                            ("dhuhr", "Dhuhr"),
                            ("asr", "Asr"),
                            ("maghrib", "Maghrib"),
                            ("isha", "Isha"),
                        ],
                        max_length=10,
                    ),
                ),
                ("adhan_time", models.TimeField()),
                (
                    "duration",
                    models.IntegerField(
                        default=30,
                        help_text="Blocked duration in minutes for this prayer",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "adhan_time"],
                "unique_together": {("date", "prayer")},
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("attended", "Attended ✅"),
                            ("absent", "Absent (No-Show) ❌"),
                            ("excused", "Excused (No Pay) 💬"),
                            ("cancelled_by_teacher", "Cancelled by Teacher 🚫"),
                        ],
                        default="scheduled",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="scheduler.student",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="RecurringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (5, "Saturday"),
                            (6, "Sunday"),
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scheduler.student",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
            },
        ),
    ]
