# Generated by Django 5.2.13 on 2026-05-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="timezone",
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="prayer_buffer_minutes",
            field=models.IntegerField(
                default=10, help_text="Buffer time after Adhan to block scheduling"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="country",
            field=models.CharField(
                choices=[
                    ("", "Select country…"),
                    ("Egypt", "🇪🇬 Egypt"),
                    ("Germany", "🇩🇪 Germany"),
                    ("France", "🇫🇷 France"),
                    ("United Kingdom", "🇬🇧 United Kingdom"),
                    ("United States", "🇺🇸 United States"),
                    ("Canada", "🇨🇦 Canada"),
                    ("Saudi Arabia", "🇸🇦 Saudi Arabia"),
                    ("UAE", "🇦🇪 UAE"),
                    ("Kuwait", "🇰🇼 Kuwait"),
                    ("Lebanon", "🇱🇧 Lebanon"),
                    ("Jordan", "🇯🇴 Jordan"),
                    ("Iraq", "🇮🇶 Iraq"),
                    ("Japan", "🇯🇵 Japan"),
                    ("China", "🇨🇳 China"),
                    ("India", "🇮🇳 India"),
                    ("Australia", "🇦🇺 Australia"),
                ],
                default="Egypt",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("attended", "Attended ✅"),
                    ("absent", "Absent (No-Show) ❌"),
                    ("excused", "Excused (No Pay) 💬"),
                    ("cancelled_by_teacher", "Cancelled by Tutor 🚫"),
                ],
                default="scheduled",
                max_length=30,
            ),
        ),
    ]
