# Generated by Django 4.0.8 on 2026-05-06 23:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_student_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable to temporarily pause this schedule'),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('skip', 'Skip Week'), ('move', 'Move Session'), ('add', 'Add Sessions')], max_length=20)),
                ('week_start_date', models.DateField(help_text='Start date (Monday) of the week affected')),
                ('move_to_date', models.DateField(blank=True, help_text='Target date for moving the session', null=True)),
                ('move_to_time', models.TimeField(blank=True, help_text='Target time for the moved session', null=True)),
                ('add_count', models.IntegerField(default=1, help_text='Number of extra sessions to add')),
                ('add_date', models.DateField(blank=True, help_text='Date to add extra sessions', null=True)),
                ('add_time', models.TimeField(blank=True, help_text='Time to add extra sessions', null=True)),
                ('reason', models.CharField(blank=True, help_text='Why this exception exists', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text='Who created this exception', max_length=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='scheduler.recurringschedule')),
            ],
            options={
                'verbose_name_plural': 'Schedule Exceptions',
                'ordering': ['week_start_date'],
            },
        ),
    ]
