# Generated by Django 5.2.13 on 2026-05-06 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_enrollment_redesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="recurring_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="scheduler.recurringschedule",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="default_session_duration",
            field=models.IntegerField(default=60, help_text="Duration in minutes"),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="duration",
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="session",
            name="is_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="session",
            name="recurring_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="scheduler.recurringschedule",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "Rescheduled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="session_duration",
            field=models.IntegerField(help_text="Duration in minutes"),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="session_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
