# Generated by Django 5.2.13 on 2026-05-03 10:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_recurringschedule_session_recurring_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=10),
        ),
    ]
